// ── campaign data ──────────────────────────────────────────────
window.WBK = {
  messages: [
    "Every night at BLVD World feels like magic!",
    "Home is wherever the Boulevard lights are.",
    "Bigger and closer to imagination. Always.",
    "One ticket. A thousand memories.",
    "We don't visit BLVD World. We live it.",
    "See you under the ferris wheel. 💜",
  ],

  stickers: ["💜", "⭐", "🎟️", "🎆", "🌙", "🎶"],

  // rides, from the official park sheet
  rides: [
    "Wave Swinger", "Turbo 360", "Drop and Twist",
    "Carousel", "Sky Loop", "Enjoy The Flight",
    "Cable Cars", "Taxi Mania", "Convoy Figure 8",
    "View Tower", "Super Fly", "Amazonia Awakens",
    "Dragons Fury", "Air Max",
  ],

  // park experiences grouped by zone, from the same sheet
  parkExperiences: [
    { zone: "Africa",     items: ["Lion Exp", "Giraffe Exp", "Bird Nest Exp", "Lemur Catta Exp", "Forest Exp", "Tours Exp"] },
    { zone: "Warzone",    items: ["Battle Dome", "Line of Fire", "Shotgun Range", "Topshot", "Battle Cart", "War Castle"] },
    { zone: "The Planet", items: ["The Dome Cinema", "Meta World", "Dolphinarium", "Swimming with Dolphins"] },
    { zone: "Egypt",      items: ["Escape Room: Secret of the Pharaoh", "The Lost Museum", "PUBG"] },
    { zone: "Italy",      items: ["Midnight Manor"] },
    { zone: "Mexico",     items: ["Doll Maker"] },
    { zone: "Courchevel", items: ["Skiing School"] },
    { zone: "Pier",       items: ["Coco Melon Exp"] },
    { zone: "T\u00fcrkiye",  items: ["Oasis"] },
    { zone: "Iran",       items: ["Pac-Man"] },
  ],

  // dining highlights, one per zone
  restaurants: [
    { name: "Najd Grill House",      zone: "Saudi Arabia", cuisine: "SAUDI",     img: "saudi.jpg",  desc: "Kabsa, mandi and mixed grills in a Najdi mud-brick courtyard." },
    { name: "Nile Terrace",          zone: "Egypt",        cuisine: "EGYPTIAN",  img: "egypt.jpg",  desc: "Koshari and grilled kofta with the pyramid lit behind you." },
    { name: "Uzung\u00f6l Restaurant", zone: "T\u00fcrkiye", cuisine: "TURKISH",   img: "turkey.jpg", desc: "Mezze, kebabs and shisha on a lantern-lit terrace." },
    { name: "Le Petit Bistro",       zone: "France",       cuisine: "FRENCH",    img: "france.jpg", desc: "Cr\u00eapes, steak frites and coffee under the tower." },
    { name: "Trattoria Bella",       zone: "Italy",        cuisine: "ITALIAN",   img: "italy.jpg",  desc: "Wood-fired pizza and gelato beside the Grand Canal." },
    { name: "Dim Sum Palace",        zone: "China",        cuisine: "CHINESE",   img: "china.jpg",  desc: "Steamer baskets and noodle bowls under the red pagoda." },
    { name: "Ramen Yokocho",         zone: "Japan",        cuisine: "JAPANESE",  img: "japan.jpg",  desc: "A narrow alley of ramen counters and taiyaki stands." },
    { name: "Route 66 Diner",        zone: "United States",cuisine: "AMERICAN",  img: "usa.jpg",    desc: "Chrome booths, burgers and milkshakes till late." },
    { name: "Cantina Azteca",        zone: "Mexico",       cuisine: "MEXICAN",   img: "mexico.jpg", desc: "Tacos and horchata below the crimson pyramid." },
    { name: "Tagine House",          zone: "Morocco",      cuisine: "MOROCCAN",  img: "park5.jpg",  desc: "Slow-cooked tagines and mint tea in a riad courtyard." },
    { name: "Korean BBQ House",      zone: "South Korea",  cuisine: "KOREAN",    img: "park6.jpg",  desc: "Tabletop grills, banchan and bingsu for dessert." },
    { name: "Taverna Blue",          zone: "Greece",       cuisine: "GREEK",      img: "park7.jpg",  desc: "Gyros, grilled halloumi and Aegean-blue shutters." },
  ],

  showsByZone: [
    { zone: "Saudi Arabia", items: [{ n: "Welcoming Roamers", t: "8:30", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Majas / Traditional Learning / Storyteller", t: "9:00", ap: "PM", m: 15, ty: "ROAMING / STAGE" }, { n: "Welcoming Roamers", t: "9:40", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Majas / Traditional Learning / Storyteller", t: "10:20", ap: "PM", m: 15, ty: "ROAMING / STAGE" }, { n: "Mesaharati", t: "10:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Welcoming Roamers", t: "11:10", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Majas / Traditional Learning / Storyteller", t: "12:10", ap: "AM", m: 15, ty: "ROAMING / STAGE" }, { n: "Mesaharati", t: "12:40", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Egypt", items: [{ n: "Full Parade", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Egyptian Servants", t: "9:05", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Greeting Parade", t: "9:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Cleopatra", t: "9:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Greeting Parade", t: "10:05", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Egyptian Servants", t: "10:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Cleopatra", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mesaharati", t: "11:20", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Full Parade", t: "11:45", ap: "PM", m: 15, ty: "ROAMING" }] },
    { zone: "Türkiye", items: [{ n: "Turkish Rovers", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "8:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "9:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "9:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Rovers", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Rovers", t: "11:15", ap: "PM", m: 15, ty: "DANCE" }, { n: "Turkish Folkloric Dance", t: "11:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Turkish Folkloric Dance", t: "12:45", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "France", items: [{ n: "Eiffel Gentalmens", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Parisian Tourists", t: "9:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "French Mime", t: "10:15", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Eiffel Gentalmens", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "French Mime", t: "11:35", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Parisian Tourists", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Eiffel Gentalmens", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Italy", items: [{ n: "Venetian Masquerade", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Italian Rhythms Of Tradition", t: "9:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Venetian Masquerade", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Italian Rhythms Of Tradition", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Venetian Masquerade", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Italian Rhythms Of Tradition", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Venetian Masquerade", t: "11:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Italian Rhythms Of Tradition", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Venetian Masquerade", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Spain", items: [{ n: "Traditional Spain Roaming", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Traditional Spain Roaming", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Spain Roaming", t: "10:10", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Spain Roaming & Couple", t: "10:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Traditional Spain Roaming", t: "11:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Spain Roaming & Couple", t: "12:15", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Greece", items: [{ n: "Empire Warriors", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mainland Greek", t: "9:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Empire Warriors", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mainland Greek", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Empire Warriors", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mainland Greek", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Empire Warriors", t: "11:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mainland Greek", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Empire Warriors", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Morocco", items: [{ n: "Ramadan Melodies", t: "9:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Dakar Esawi", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Ramadan Melodies", t: "10:50", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Dakar Esawi", t: "11:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Ramadan Melodies", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Levant", items: [{ n: "Mesaharati", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Ramadan Nights", t: "9:20", ap: "PM", m: 15, ty: "STAGE" }, { n: "Storyteller", t: "9:35", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Ramadan Nights", t: "10:25", ap: "PM", m: 15, ty: "STAGE" }, { n: "Mesaharati", t: "10:40", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Ramadan Nights", t: "11:30", ap: "PM", m: 15, ty: "STAGE" }, { n: "Storyteller", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Ramadan Nights", t: "12:30", ap: "AM", m: 15, ty: "STAGE" }] },
    { zone: "India", items: [{ n: "Bollywood Parade", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Global Village Greeting", t: "8:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Bollywood Parade", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Global Village Greeting", t: "9:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Bollywood Parade", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Global Village Greeting", t: "10:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Bollywood Parade", t: "11:15", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Global Village Greeting", t: "11:40", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Bollywood Parade", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "China", items: [{ n: "Dragon / Mini-Circus", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Lion Dance", t: "8:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "China Masks Inspiration", t: "9:00", ap: "PM", m: 15, ty: "STAGE" }, { n: "Dragon / Mini-Circus", t: "9:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Lion Dance", t: "9:45", ap: "PM", m: 10, ty: "ROAMING" }, { n: "China Masks Inspiration", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Dragon / Mini-Circus", t: "10:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Lion Dance", t: "10:45", ap: "PM", m: 10, ty: "ROAMING" }, { n: "China Masks Inspiration", t: "11:05", ap: "PM", m: 15, ty: "STAGE" }, { n: "Dragon / Mini-Circus", t: "11:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "China Masks Inspiration", t: "12:15", ap: "AM", m: 15, ty: "STAGE" }, { n: "Lion Dance", t: "12:30", ap: "AM", m: 10, ty: "ROAMING" }, { n: "Dragon / Mini-Circus", t: "12:45", ap: "AM", m: 15, ty: "STAGE" }] },
    { zone: "Japan", items: [{ n: "Full Parade", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Samurai & Geisha", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Japanese Cat / Tails", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Samurai & Geisha", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Japanese Cat / Tails", t: "11:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Full Parade", t: "12:45", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Korea", items: [{ n: "Korea Roaming", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Korea Roaming", t: "9:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Korea Roaming", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Korea Roaming", t: "11:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Korea Roaming", t: "12:45", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Indonesia", items: [{ n: "Indonesia Roaming", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Indonesia Greeting", t: "9:00", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Indonesia Roaming", t: "9:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Indonesia Greeting", t: "9:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Indonesia Roaming", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Indonesia Greeting", t: "10:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Indonesia Roaming", t: "11:25", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Indonesia Greeting", t: "11:45", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Indonesia Roaming", t: "12:45", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Asia", items: [{ n: "Greeting", t: "8:30", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "9:00", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Greeting", t: "9:50", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "10:30", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "11:00", ap: "PM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "11:30", ap: "PM", m: 15, ty: "STAGE" }, { n: "Greeting", t: "12:00", ap: "AM", m: 10, ty: "ROAMING" }, { n: "Greeting", t: "12:30", ap: "AM", m: 15, ty: "STAGE" }] },
    { zone: "USA", items: [{ n: "Western Rhythms", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Cowboy Mascots", t: "9:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Swinging Polka Nights", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Western Rhythms", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Cowboy Mascots", t: "10:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Western Rhythms", t: "11:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Cowboy Mascots", t: "11:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Swinging Polka Nightsr", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Cowboy Mascots", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Mexico", items: [{ n: "Achi Band / Traditional Mexico Roaming", t: "8:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mexican Mariachi Band", t: "9:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Show", t: "10:20", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mexican Mariachi Band", t: "10:55", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Mexican Mariachi Band", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Roaming Show", t: "12:30", ap: "AM", m: 15, ty: "ROAMING" }] },
    { zone: "Iran", items: [{ n: "Iran Roaming", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Iran Roaming", t: "9:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Iran Roaming", t: "10:45", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Iran Roaming", t: "11:45", ap: "PM", m: 15, ty: "ROAMING" }] },
    { zone: "Africa", items: [{ n: "Roaming Africans", t: "8:30", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans/ Drums", t: "8:50", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans", t: "9:10", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans", t: "10:00", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans/ Drums", t: "10:20", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans", t: "10:50", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans", t: "11:35", ap: "PM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans/ Drums", t: "12:00", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Roaming Show", t: "12:25", ap: "AM", m: 15, ty: "ROAMING" }, { n: "Roaming Africans/ Drums", t: "12:45", ap: "AM", m: 15, ty: "ROAMING" }] },
  ],

  faqs: [
    { q: "Where is BLVD World?",
      a: "BLVD World sits in Riyadh's Boulevard City district, part of Riyadh Season. Parking and ride-hailing drop-offs are signposted from the main gates." },
    { q: "What does the entry ticket include?",
      a: "Entry gives you access to the park and every walkable zone \u2014 the streets, plazas, souks and light shows. Individual rides, dining and ticketed experiences are booked separately." },
    { q: "What is the difference between entry and entry + experience?",
      a: "An entry + experience ticket bundles your park entry with one booked experience, so you pay once and skip a second checkout. It always includes entry." },
    { q: "What are the opening hours?",
      a: "The park opens in the late afternoon and runs past midnight through the Season. Exact times shift by day, so check your ticket for the night you're visiting." },
    { q: "Is it suitable for children?",
      a: "Yes \u2014 most zones are family areas, with carousels, arcades and dining alongside the bigger rides. Individual thrill rides carry their own height and age limits." },
    { q: "How many zones are there?",
      a: "Twenty country zones, from Saudi heritage streets and an Egyptian pyramid to Venetian canals, a Tokyo arcade street and an immersive Africa zone." },
    { q: "Can I re-enter if I leave?",
      a: "Standard entry tickets are valid for a single entry per day. If you plan to come and go, ask about multi-entry options at the gate." },
    { q: "Can I change or refund a booking?",
      a: "Changes and refunds follow the policy shown at checkout on webook.com, which varies by ticket type. Check the terms on your confirmation email." },
  ],

  // park zones, pinned to their real countries on the globe
  zones: [
    { name: "Saudi Arabia",  lat: 24.7,  lon: 46.7,   blurb: "Local heritage, food and traditional performances." , imgs: ["saudi.jpg", "park2.jpg", "park5.jpg"], attractions: ["Najdi Heritage Village", "Falcon Show Arena", "Traditional Ardah Stage"], food: ["Najd Grill House", "Qahwa & Dates Lounge", "Kabsa Kitchen"], rides: ["Desert Rover Coaster", "Camel Carousel"] },
    { name: "Egypt",         lat: 26.8,  lon: 30.8,   blurb: "Iconic architecture and a PUBG experience zone." , imgs: ["egypt.jpg", "park4.jpg", "park7.jpg"], attractions: ["Pyramid Light Show", "PUBG Experience Zone", "Sphinx Plaza"], food: ["Nile Terrace", "Koshari Corner"], rides: ["Pharaoh's Drop Tower", "Scarab Spinner"] },
    { name: "France",        lat: 46.6,  lon: 2.2,    blurb: "An Eiffel Tower replica with Courchevel styling." , imgs: ["france.jpg", "park1.jpg", "park3.jpg"], attractions: ["Eiffel Tower Replica", "Courchevel Snow Deck", "Street Mime Quarter"], food: ["Le Petit Bistro", "Cr\u00eaperie du Parc", "Champs Caf\u00e9"], rides: ["Grand Carousel", "Balloon Ascent"] },
    { name: "United Kingdom",lat: 54.0,  lon: -2.0,   blurb: "A Big Ben replica and red telephone booths." , imgs: ["park6.jpg", "park2.jpg", "park3.jpg"], attractions: ["Big Ben Replica", "Red Phone Box Row", "Changing of the Guard"], food: ["The Crown Pub", "Fish & Chips Co."], rides: ["London Eye Wheel", "Double-Decker Dodgems"] },
    { name: "United States", lat: 39.8,  lon: -98.6,  blurb: "Classic American streets and pop culture." , imgs: ["usa.jpg", "park1.jpg", "park6.jpg"], attractions: ["Route 66 Main Street", "Hollywood Walk", "Comic Pop Gallery"], food: ["Route 66 Diner", "Smokehouse BBQ", "Shake Shack Bar"], rides: ["Cyclone Coaster", "Bumper Cars"] },
    { name: "Italy",         lat: 42.8,  lon: 12.6,   blurb: "European architecture, canals and plazas." , imgs: ["italy.jpg", "park7.jpg", "park5.jpg"], attractions: ["The Grand Canal", "Campanile Tower", "Piazza Fountain"], food: ["Trattoria Bella", "Gelateria Roma", "Pizza al Taglio"], rides: ["Gondola Ride", "Venetian Swing"] },
    { name: "Spain",         lat: 40.4,  lon: -3.7,   blurb: "Sun-warmed plazas and Andalusian arches." , imgs: ["park3.jpg", "park5.jpg", "park1.jpg"], attractions: ["Plaza de Toros Gate", "Flamenco Courtyard", "Andalusian Arches"], food: ["Tapas Barra", "Churros & Chocolate"], rides: ["Matador Spin", "Fiesta Twister"] },
    { name: "Greece",        lat: 39.0,  lon: 22.0,   blurb: "Whitewashed Mediterranean charm." , imgs: ["park7.jpg", "park6.jpg", "park2.jpg"], attractions: ["Santorini Steps", "Whitewashed Chapel", "Aegean Viewpoint"], food: ["Taverna Blue", "Gyros Grill"], rides: ["Olympus Freefall", "Aegean Wave Swing"] },
    { name: "Morocco",       lat: 31.8,  lon: -7.1,   blurb: "North African souks and lantern light." , imgs: ["park5.jpg", "park4.jpg", "park1.jpg"], attractions: ["Marrakech Souk", "Lantern Alley", "Riad Courtyard"], food: ["Tagine House", "Mint Tea Terrace"], rides: ["Magic Carpet Ride", "Souk Spinner"] },
    { name: "India",         lat: 21.0,  lon: 78.0,   blurb: "Palace façades and street food lanes." , imgs: ["park2.jpg", "park6.jpg", "park3.jpg"], attractions: ["Taj Mahal Replica", "Palace Gardens", "Bollywood Stage"], food: ["Spice Route Kitchen", "Chai & Chaat Bar"], rides: ["Elephant Carousel", "Maharaja Express"] },
    { name: "China",         lat: 35.0,  lon: 104.0,  blurb: "Red pagodas and lantern markets." , imgs: ["china.jpg", "park3.jpg", "park7.jpg"], attractions: ["Chinatown Gate", "Red Pagoda", "Lion Dance Square"], food: ["Dim Sum Palace", "Noodle Bar", "Bubble Tea House"], rides: ["Dragon Coaster", "Lantern Wheel"] },
    { name: "Japan",         lat: 36.2,  lon: 138.3,  blurb: "Neon arcades and Tokyo street food." , imgs: ["japan.jpg", "park1.jpg", "park6.jpg"], attractions: ["Tokyo Street", "Grendizer Statue", "Retro Arcade Hall"], food: ["Ramen Yokocho", "Sushi Counter", "Taiyaki Stand"], rides: ["Neon Drift Racers", "Robot Drop"] },
    { name: "Indonesia",     lat: -2.5,  lon: 118.0,  blurb: "Island colour and tropical craft." , imgs: ["park1.jpg", "park7.jpg", "park4.jpg"], attractions: ["Bali Water Garden", "Batik Craft House", "Island Dance Stage"], food: ["Warung Nasi", "Satay Grill"], rides: ["Volcano Splash", "Tiki Swing"] },
    { name: "South Korea",   lat: 36.5,  lon: 127.9,  blurb: "K-pop energy and Seoul night bites." , imgs: ["park6.jpg", "park3.jpg", "park2.jpg"], attractions: ["K-Pop Plaza", "Hanok Lane", "Seoul Neon Alley"], food: ["Korean BBQ House", "Bingsu Bar", "Street Toast Stand"], rides: ["Hallyu Spin", "Seoul Sky Tower"] },
    { name: "Mexico",        lat: 23.6,  lon: -102.5, blurb: "A Mayan temple lit crimson above the lagoon." , imgs: ["mexico.jpg", "park5.jpg", "park4.jpg"], attractions: ["The Red Pyramid", "Mayan Ruins Walk", "Mariachi Square"], food: ["Cantina Azteca", "Taqueria del Sol"], rides: ["Chichen Drop", "Aztec Rapids"] },
    { name: "Kuwait",        lat: 29.3,  lon: 47.5,   blurb: "Gulf towers and a coastal promenade." , imgs: ["park4.jpg", "park2.jpg", "park7.jpg"], attractions: ["Kuwait Towers Replica", "Gulf Promenade", "Pearl Diving Exhibit"], food: ["Machboos House", "Gulf Seafood Deck"], rides: ["Dhow Boat Ride", "Pearl Spinner"] },
    { name: "Thailand",      lat: 15.9,  lon: 101.0,  blurb: "Floating-market flavours and temple gold." , imgs: ["park7.jpg", "park1.jpg", "park5.jpg"], attractions: ["Floating Market", "Grand Temple Replica", "Muay Thai Ring"], food: ["Pad Thai Street", "Mango Sticky Rice Bar"], rides: ["Longtail Boat Ride", "Tuk-Tuk Dodgems"] },
    { name: "Türkiye",       lat: 39.0,  lon: 35.2,   blurb: "Uzungöl terraces, folk dance and shisha." , imgs: ["turkey.jpg", "park6.jpg", "park2.jpg"], attractions: ["Uzung\u00f6l Terraces", "Galata Tower Replica", "Whirling Dervish Stage"], food: ["Uzung\u00f6l Restaurant & Shisha", "Baklava House", "Turkish Coffee Nook"], rides: ["Bosphorus Flyer", "Ottoman Carousel"] },
    { name: "Iran",          lat: 32.4,  lon: 53.7,   blurb: "Tiled courtyards and a Pac-Man game experience." , imgs: ["park5.jpg", "park3.jpg", "park4.jpg"], attractions: ["Tiled Courtyard", "Pac-Man Game Experience", "Persian Carpet Hall"], food: ["Kebab Bazaar", "Saffron Tea Room"], rides: ["Persian Rug Glider", "Bazaar Spinner"] },
    { name: "Africa",        lat: 0.0,   lon: 20.0,   blurb: "An immersive safari-scale Africa zone." , imgs: ["park8.jpg", "park6.jpg", "park1.jpg"], attractions: ["Immersive Safari Trail", "Savanna Drum Circle", "Tribal Art Market"], food: ["Safari Grill", "Baobab Juice Bar"], rides: ["Safari Jeep Adventure", "Jungle Rapids"] },
  ],

  // premium experiences — every ticket includes park entry
  experiences: [
    { img: "exp/snow.jpg",      title: "Skiing School",     zone: "Courchevel", price: 260, blurb: "Real snow, real instructors — learn to ski inside the dome." },
    { img: "exp/pyramid.jpg",   title: "Escape Room",        zone: "Egypt",      price: 180, blurb: "Secret of the Pharaoh: sixty minutes to break out of the tomb." },
    { img: "zones/park4.jpg",     title: "Dolphinarium",       zone: "The Planet", price: 220, blurb: "A full dolphin show under the dome, twice nightly." },
    { img: "zones/park7.jpg",     title: "Swimming with Dolphins", zone: "The Planet", price: 480, blurb: "Get in the water and meet them up close." },
    { img: "zones/park2.jpg",     title: "Battle Dome",        zone: "Warzone",    price: 150, blurb: "Team laser combat in a floodlit arena." },
    { img: "exp/gondola.jpg",   title: "Midnight Manor",     zone: "Italy",      price: 140, blurb: "A haunted walk-through where the house pushes back." },
    { img: "zones/park3.jpg",     title: "The Dome Cinema",    zone: "The Planet", price: 120, blurb: "Films projected across a full wraparound dome." },
    { img: "zones/park1.jpg",     title: "Lion Experience",    zone: "Africa",     price: 200, blurb: "Come face to face with the pride on the safari trail." },
    { img: "zones/park5.jpg",     title: "Pac-Man",            zone: "Iran",       price: 110, blurb: "Step inside the maze — you are the yellow one." },
    { img: "zones/egypt.jpg",     title: "PUBG",               zone: "Egypt",      price: 160, blurb: "The battle royale, staged for real among the ruins." },
  ],

  letters: [
    { msg: "Every night at BLVD World feels like magic!", who: "Noura", country: "Saudi Arabia", lat: 24.7, lon: 46.7 },
    { msg: "Flew in just for BLVD World. Zero regrets!", who: "Jimin S.", country: "South Korea", lat: 37.5, lon: 127.0 },
    { msg: "One ticket. A thousand memories.", who: "Omar", country: "Egypt", lat: 30.0, lon: 31.2 },
    { msg: "The lights, the music, the people. Unreal.", who: "Sarah", country: "UAE", lat: 25.2, lon: 55.3 },
    { msg: "We don't visit BLVD World. We live it.", who: "Faisal", country: "Saudi Arabia", lat: 21.5, lon: 39.2 },
    { msg: "See you under the ferris wheel. 💜", who: "Yuki", country: "Japan", lat: 35.7, lon: 139.7 },
    { msg: "Best night of my entire year. Thank you!", who: "Lucas", country: "Brazil", lat: -23.5, lon: -46.6 },
    { msg: "Home is wherever the Boulevard lights are.", who: "Amira", country: "Kuwait", lat: 29.4, lon: 48.0 },
    { msg: "Counting days until the next Season!", who: "Priya", country: "India", lat: 19.1, lon: 72.9 },
    { msg: "You turned our city into a love letter.", who: "Dana", country: "Bahrain", lat: 26.2, lon: 50.6 },
    { msg: "Ten rides. One night. Still not enough.", who: "Mike", country: "USA", lat: 34.05, lon: -118.24 },
    { msg: "The fireworks live in my head rent-free.", who: "Ella", country: "UK", lat: 51.5, lon: -0.13 },
  ],
};
